# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cons.xdc

# IP: ip/fir_compiler_2/fir_compiler_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_compiler_2 || ORIG_REF_NAME==fir_compiler_2}]

# IP: ip/fir_compiler_1/fir_compiler_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_compiler_1 || ORIG_REF_NAME==fir_compiler_1}]

# IP: ip/fir_compiler_0/fir_compiler_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_compiler_0 || ORIG_REF_NAME==fir_compiler_0}]

# IP: ip/dds_compiler_1/dds_compiler_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_compiler_1 || ORIG_REF_NAME==dds_compiler_1}]

# IP: ip/dds_compiler_0/dds_compiler_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_compiler_0 || ORIG_REF_NAME==dds_compiler_0}]

# IP: ip/ila_0/ila_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0}]

# XDC: ip/fir_compiler_2/fir_compiler_v7_2_5/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_compiler_2 || ORIG_REF_NAME==fir_compiler_2}] {/U0 }]/U0 ]]

# XDC: ip/fir_compiler_1/fir_compiler_v7_2_5/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_compiler_1 || ORIG_REF_NAME==fir_compiler_1}] {/U0 }]/U0 ]]

# XDC: ip/fir_compiler_0/fir_compiler_v7_2_5/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_compiler_0 || ORIG_REF_NAME==fir_compiler_0}] {/U0 }]/U0 ]]

# XDC: ip/ila_0/ila_v6_0/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0}]

# XDC: ip/ila_0/ila_0_ooc.xdc
