# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/FPGA/Vivado/FSK/FSK.cache/wt [current_project]
set_property parent.project_path D:/FPGA/Vivado/FSK/FSK.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files D:/FPGA/Vivado/FSK/bandpass2t3.coe
add_files D:/FPGA/Vivado/FSK/bandpass9t10.coe
add_files D:/FPGA/Vivado/FSK/bandpass8to9.coe
add_files D:/FPGA/Vivado/FSK/bandpass4t6.coe
add_files D:/FPGA/Vivado/FSK/lowpass2.coe
read_ip D:/FPGA/Vivado/FSK/FSK.srcs/sources_1/ip/fir_compiler_2/fir_compiler_2.xci
set_property used_in_implementation false [get_files -all d:/FPGA/Vivado/FSK/FSK.srcs/sources_1/ip/fir_compiler_2/fir_compiler_v7_2_5/constraints/fir_compiler_v7_2.xdc]
set_property is_locked true [get_files D:/FPGA/Vivado/FSK/FSK.srcs/sources_1/ip/fir_compiler_2/fir_compiler_2.xci]

read_ip D:/FPGA/Vivado/FSK/FSK.srcs/sources_1/ip/fir_compiler_1/fir_compiler_1.xci
set_property used_in_implementation false [get_files -all d:/FPGA/Vivado/FSK/FSK.srcs/sources_1/ip/fir_compiler_1/fir_compiler_v7_2_5/constraints/fir_compiler_v7_2.xdc]
set_property is_locked true [get_files D:/FPGA/Vivado/FSK/FSK.srcs/sources_1/ip/fir_compiler_1/fir_compiler_1.xci]

read_ip D:/FPGA/Vivado/FSK/FSK.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0.xci
set_property used_in_implementation false [get_files -all d:/FPGA/Vivado/FSK/FSK.srcs/sources_1/ip/fir_compiler_0/fir_compiler_v7_2_5/constraints/fir_compiler_v7_2.xdc]
set_property is_locked true [get_files D:/FPGA/Vivado/FSK/FSK.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0.xci]

read_ip D:/FPGA/Vivado/FSK/FSK.srcs/sources_1/ip/dds_compiler_1/dds_compiler_1.xci
set_property is_locked true [get_files D:/FPGA/Vivado/FSK/FSK.srcs/sources_1/ip/dds_compiler_1/dds_compiler_1.xci]

read_ip D:/FPGA/Vivado/FSK/FSK.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0.xci
set_property is_locked true [get_files D:/FPGA/Vivado/FSK/FSK.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0.xci]

read_ip d:/FPGA/Vivado/FSK/FSK.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_implementation false [get_files -all d:/FPGA/Vivado/FSK/FSK.srcs/sources_1/ip/ila_0/ila_v6_0/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Vivado/FSK/FSK.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc]
set_property is_locked true [get_files d:/FPGA/Vivado/FSK/FSK.srcs/sources_1/ip/ila_0/ila_0.xci]

read_verilog -library xil_defaultlib {
  D:/FPGA/Vivado/FSK/FSK.srcs/sources_1/new/FSK_demod.v
  D:/FPGA/Vivado/FSK/FSK.srcs/sources_1/new/FSK_mod.v
  D:/FPGA/Vivado/FSK/FSK.srcs/sources_1/new/top.v
}
read_xdc D:/FPGA/Vivado/FSK/FSK.srcs/constrs_1/new/cons.xdc
set_property used_in_implementation false [get_files D:/FPGA/Vivado/FSK/FSK.srcs/constrs_1/new/cons.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top top -part xc7z020clg400-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
