set_property SRC_FILE_INFO {cfile:D:/FPGA/Vivado/FSK/FSK.srcs/constrs_1/new/cons.xdc rfile:../../../FSK.srcs/constrs_1/new/cons.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property DIRECTION IN [get_ports sys_clk]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H16 [get_ports {sys_clk}]
